//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estupendo, tengo los datos necesarios. El equipo de entrenadores sabrá cómo darles buen uso. ¡¡Gracias!!.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola de nuevo. Bienvenido a TrainingBotApp, la app que se preocupa por tu entrenamiento cada día..
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si te parece vamos a averiguar qué tal fue tu entrenamiento..
        /// </summary>
        internal static string LetsStart {
            get {
                return ResourceManager.GetString("LetsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo te lo has pasado en la sesión de hoy? Expresate como quieras..
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Y cómo crees que ha sido tu entrenamiento?.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaya, siento que no sean especialmente positivas tus sensaciones..
        /// </summary>
        internal static string Response1Bad {
            get {
                return ResourceManager.GetString("Response1Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genial, si tú estás contento con el resultado me pones también contento a mí..
        /// </summary>
        internal static string Response1Good {
            get {
                return ResourceManager.GetString("Response1Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que no has tenido sensación de haber aprovechado el entrenamiento demasiado... .
        /// </summary>
        internal static string Response2Bad {
            get {
                return ResourceManager.GetString("Response2Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me alegro de que te sientas bien con el esfuerzo..
        /// </summary>
        internal static string Response2Good {
            get {
                return ResourceManager.GetString("Response2Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramos la encuesta aquí que no he podido comunicarme con la central. Intentalo más tarde. ¡Muchas gracias!.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
    }
}
